#!/bin/sh
export BOARD="$1"
THREAD="$2"
[ "$XDG_DOWNLOAD_DIR" = "" ] && DOWNLOAD="${HOME}/4chan-dl" || DOWNLOAD="${XDG_DOWNLOAD_DIR}/4chan-dl"
OUTPUT="${DOWNLOAD}/${BOARD}/${THREAD}"

API_URL="https://a.4cdn.org/${BOARD}/thread/${THREAD}.json"
TMPFILE="/tmp/${THREAD}.json"

_help() {
	printf "\033[1;32m4chan Downloader\033[0m 🍀 by \033[1;34mswindlesmccoop\033[0m
-------------------------------------
Usage: ./dlthread [board] [thread id]\n"
	exit
}

case "$1" in
	-h|"") _help ;;
esac

curl -s "$API_URL" | jq > "$TMPFILE"
TITLE="$(grep '"sub.*' "$TMPFILE" | sed -e 's/      "sub": "//; s/",//')"

# $1 = OG filename, $2 = target filename, $3 = extension
ARRAY="$(grep -P '"filename":|"ext":|"tim":' $TMPFILE | awk 'BEGIN { RS=","; OFS=" " } /"filename":/ { sub(/"/, "", $2); filename=$2 } /"ext":/ { sub(/"/, "", $2); ext=$2 } /"tim":/ { sub(/"/, "", $2); sub(/,$/, "", $2); tim=$2; gsub(/\\n/,"",ext); gsub(/"/, "", filename); gsub(/"/, "", ext); print filename, tim, ext }')"

mkdir -p "$OUTPUT" && cd "$OUTPUT"

wgetcmd() {
	printf "Downloading \033[0;32m${1}${3}\033[0m..."
	if [ -f "${1}${3}" ]; then
		printf "already exists, skipping.\n"
		continue
	else
		wget -q -O "${1}${3}" "https://i.4cdn.org/${BOARD}/${2}${3}"
		#curl -Lso "${1}${3}" "https://i.4cdn.org/${BOARD}/${2}${3}"
		printf "done.\n"
	fi
}

export -f wgetcmd
printf "%s\n" "$ARRAY" | parallel -j$(nproc) --colsep ' ' wgetcmd {1} {2} {3}